development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://vvlomwhdnqdbte:RcQdJO3ZMyJ3qsG9n5ylt-_PCG@ec2-174-129-4-75.compute-1.amazonaws.com:5432/dqok8l008cqip

